### ISSUE TITLE
Mananode stat calculation incorrect

### ISSUE THREAD

**Issue by SteelGram** [SapiensAnatis/DragaliaAPI#29]
Describe the bug
Stat gain ain't right

On branch
dev-steelgram

To Reproduce
Unlock mananodes

Expected behavior
Correct stat gain

Additional context
Probably broke during one of the adjustments

**Comment by SapiensAnatis** [comment]
Bug can no longer be reproduced but will keep an eye out for this issue

**Comment by SapiensAnatis** [comment]
Closing until this has a definite occurrence and reproduction steps
