### ISSUE TITLE
Wyrmprint dragon prep abilities don't work at the start of a quest

### ISSUE THREAD

**Issue by Nightmerp** [SapiensAnatis/DragaliaAPI#78]
**Describe the bug**
The wyrmprints Dragon's Nest and Dragon Arcanum don't seem to have any effect at the beginning of a quest. However, dragons with such abilities, Bahamut/Ramiel/Elysium/Pbrun, as well as character abilities like Alberius' A1 work as expected when in the main party.

**On branch**
Develop live 06/01/2023

**To Reproduce**
1. Equip Dragon's Nest/Dragon Arcanum on any character without innate dragon prep and start a quest.

**Expected behavior**
The dragon gauge should start at a boosted amount depending on how many copies the team has equipped.

**Additional context**
No gauge increase shown in quest
![image](https://user-images.githubusercontent.com/43102229/211120765-a6d76d32-c63d-46bd-ae57-9ef960c107e6.png)

Dragon's nest is equipped
![image](https://user-images.githubusercontent.com/43102229/211120838-f15d7f55-470f-4987-b389-a7bf7ebf7c1e.png)

**Comment by SapiensAnatis** [comment]
Investigated this: it transpires we are sending the levels of each ability as 0 because we lack this information in the DB. Will be fixed when wyrmprints get some attention whenever upgrading for these is implemented. For now it may be worth adding a default assignment of 3 to the levels
